name = "ChemistryQuantitativeAnalysisUI"
uuid = "972148b6-472c-424e-8065-54bf210c1201"
authors = ["Yu-Fong Peng <sciphypar@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
